github.com:
    users:
        PROJECT01GALAHADD:
            oauth_token: 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
    oauth_token: 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
    user: PROJECT01GALAHADD
